-- Seed shop_items table with initial products (correct types: sizes=text[], colors=jsonb, images=jsonb)

INSERT INTO public.shop_items (
  name, description, price_usd, category, product_type, 
  sizes, colors, images, material_info, shipping_info, 
  stock_quantity, is_active
) VALUES
(
  'HBCU Grey Premium T-Shirt',
  'Celebrate HBCU pride with this premium grey t-shirt featuring bold graphics',
  29.99,
  'HBCU',
  'apparel',
  ARRAY['S', 'M', 'L', 'XL', '2XL'],
  '["Grey"]'::jsonb,
  '{"main": "/src/assets/shop/hbcu-grey-shirt.png", "back": "/src/assets/shop/hbcu-grey-shirt-back.png", "detail": "/src/assets/shop/hbcu-grey-shirt-detail.png", "side": "/src/assets/shop/hbcu-grey-shirt-side.png"}'::jsonb,
  '100% Premium Cotton, Pre-shrunk',
  'Ships within 3-5 business days. Free shipping on orders over $50',
  100,
  true
),
(
  'HBCU Black Premium T-Shirt 2',
  'Bold HBCU statement tee in classic black with premium construction',
  29.99,
  'HBCU',
  'apparel',
  ARRAY['S', 'M', 'L', 'XL', '2XL'],
  '["Black"]'::jsonb,
  '{"main": "/src/assets/shop/hbcu-black-shirt-2.png", "back": "/src/assets/shop/hbcu-black-shirt-2-back.png", "detail": "/src/assets/shop/hbcu-black-shirt-2-detail.png", "side": "/src/assets/shop/hbcu-black-shirt-2-side.png"}'::jsonb,
  '100% Premium Cotton, Pre-shrunk',
  'Ships within 3-5 business days. Free shipping on orders over $50',
  100,
  true
),
(
  'HBCU Camo Premium T-Shirt',
  'Stand out with this unique HBCU camo design tee',
  34.99,
  'HBCU',
  'apparel',
  ARRAY['S', 'M', 'L', 'XL', '2XL'],
  '["Camo"]'::jsonb,
  '{"main": "/src/assets/shop/hbcu-camo-shirt.png", "back": "/src/assets/shop/hbcu-camo-shirt-back.png", "detail": "/src/assets/shop/hbcu-camo-shirt-detail.png", "side": "/src/assets/shop/hbcu-camo-shirt-side.png"}'::jsonb,
  '100% Premium Cotton, Pre-shrunk',
  'Ships within 3-5 business days. Free shipping on orders over $50',
  75,
  true
),
(
  'HBCU Black Hoodie Premium 2',
  'Premium black hoodie with bold HBCU graphics',
  59.99,
  'HBCU',
  'apparel',
  ARRAY['S', 'M', 'L', 'XL', '2XL'],
  '["Black"]'::jsonb,
  '{"main": "/src/assets/shop/black-hoodie-2.png", "back": "/src/assets/shop/black-hoodie-2-back.png", "detail": "/src/assets/shop/black-hoodie-2-detail.png", "side": "/src/assets/shop/black-hoodie-2-side.png"}'::jsonb,
  '80% Cotton, 20% Polyester fleece blend',
  'Ships within 3-5 business days. Free shipping on orders over $50',
  50,
  true
),
(
  'NCRF Black Premium T-Shirt',
  'Rep NCRF with this sleek black premium tee',
  29.99,
  'NCRF',
  'apparel',
  ARRAY['S', 'M', 'L', 'XL', '2XL'],
  '["Black"]'::jsonb,
  '{"main": "/src/assets/shop/ncrf-black-shirt.png"}'::jsonb,
  '100% Premium Cotton, Pre-shrunk',
  'Ships within 3-5 business days. Free shipping on orders over $50',
  100,
  true
),
(
  'NCRF Black Premium T-Shirt 2',
  'Alternative NCRF design in classic black',
  29.99,
  'NCRF',
  'apparel',
  ARRAY['S', 'M', 'L', 'XL', '2XL'],
  '["Black"]'::jsonb,
  '{"main": "/src/assets/shop/ncrf-black-shirt-2.png", "back": "/src/assets/shop/ncrf-black-shirt-2-back.png", "detail": "/src/assets/shop/ncrf-black-shirt-2-detail.png", "side": "/src/assets/shop/ncrf-black-shirt-2-side.png"}'::jsonb,
  '100% Premium Cotton, Pre-shrunk',
  'Ships within 3-5 business days. Free shipping on orders over $50',
  100,
  true
),
(
  'BCE Black T-Shirt',
  'Show your BCE pride with this classic black tee',
  24.99,
  'BCE',
  'apparel',
  ARRAY['S', 'M', 'L', 'XL', '2XL'],
  '["Black"]'::jsonb,
  '{"main": "/src/assets/shop/bce-black-shirt.png"}'::jsonb,
  '100% Cotton',
  'Ships within 3-5 business days. Free shipping on orders over $50',
  100,
  true
),
(
  'BCE Black & Green T-Shirt',
  'BCE signature colors in a bold design',
  24.99,
  'BCE',
  'apparel',
  ARRAY['S', 'M', 'L', 'XL', '2XL'],
  '["Black", "Green"]'::jsonb,
  '{"main": "/src/assets/shop/bce-black-shirt-green.png"}'::jsonb,
  '100% Cotton',
  'Ships within 3-5 business days. Free shipping on orders over $50',
  100,
  true
),
(
  'Black Classic T-Shirt',
  'Timeless black tee for everyday wear',
  24.99,
  'LATINO',
  'apparel',
  ARRAY['S', 'M', 'L', 'XL', '2XL'],
  '["Black"]'::jsonb,
  '{"main": "/src/assets/shop/black-shirt-1.png"}'::jsonb,
  '100% Cotton',
  'Ships within 3-5 business days. Free shipping on orders over $50',
  150,
  true
),
(
  'Grey Essential T-Shirt',
  'Versatile grey tee that goes with everything',
  24.99,
  'LATINO',
  'apparel',
  ARRAY['S', 'M', 'L', 'XL', '2XL'],
  '["Grey"]'::jsonb,
  '{"main": "/src/assets/shop/grey-shirt.png"}'::jsonb,
  '100% Cotton',
  'Ships within 3-5 business days. Free shipping on orders over $50',
  150,
  true
),
(
  'Red Statement T-Shirt',
  'Make a statement with this vibrant red tee',
  24.99,
  'LATINO',
  'apparel',
  ARRAY['S', 'M', 'L', 'XL', '2XL'],
  '["Red"]'::jsonb,
  '{"main": "/src/assets/shop/red-shirt.png"}'::jsonb,
  '100% Cotton',
  'Ships within 3-5 business days. Free shipping on orders over $50',
  125,
  true
),
(
  'Red Comfort Sweater',
  'Cozy red sweater for cooler days',
  44.99,
  'LATINO',
  'apparel',
  ARRAY['S', 'M', 'L', 'XL', '2XL'],
  '["Red"]'::jsonb,
  '{"main": "/src/assets/shop/red-sweater.png"}'::jsonb,
  '70% Cotton, 30% Polyester blend',
  'Ships within 3-5 business days. Free shipping on orders over $50',
  75,
  true
),
(
  'Classic Black Hoodie',
  'Essential black hoodie for any wardrobe',
  54.99,
  'SAP',
  'apparel',
  ARRAY['S', 'M', 'L', 'XL', '2XL'],
  '["Black"]'::jsonb,
  '{"main": "/src/assets/shop/black-hoodie.png"}'::jsonb,
  '80% Cotton, 20% Polyester fleece blend',
  'Ships within 3-5 business days. Free shipping on orders over $50',
  100,
  true
),
(
  'STEAM Black Premium T-Shirt',
  'Celebrate STEAM education with this premium black tee',
  29.99,
  'STEAM',
  'apparel',
  ARRAY['S', 'M', 'L', 'XL', '2XL'],
  '["Black"]'::jsonb,
  '{"main": "/src/assets/shop/steam-black-shirt.png"}'::jsonb,
  '100% Premium Cotton, Pre-shrunk',
  'Ships within 3-5 business days. Free shipping on orders over $50',
  100,
  true
);