-- Seed high school data (20 entries with national coverage)
INSERT INTO public.school_database (
  school_name, school_type, city, state, region, grade_levels, programs_offered, athletic_programs,
  special_programs, website, contact_email, contact_phone, verification_status, data_source, is_active
) VALUES
('Hoover High School', 'High School', 'Hoover', 'AL', 'South', ARRAY['9-12'], ARRAY['College Prep', 'AP Courses', 'STEM'], ARRAY['Football', 'Basketball', 'Baseball', 'Soccer'], ARRAY['AP', 'Dual Enrollment'], 'https://www.hoovercityschools.net/hhs', 'hhs@hoovercityschools.net', '(205) 439-1000', 'verified', 'nces', true),
('Bartlett High School', 'High School', 'Anchorage', 'AK', 'West', ARRAY['9-12'], ARRAY['College Prep', 'AP Courses', 'CTE'], ARRAY['Hockey', 'Basketball', 'Skiing', 'Wrestling'], ARRAY['AP', 'Career Tech'], 'https://www.asdk12.org/bartlett', 'bartlett@asdk12.org', '(907) 742-0500', 'verified', 'nces', true),
('Brophy Prep', 'High School', 'Phoenix', 'AZ', 'West', ARRAY['9-12'], ARRAY['College Prep', 'AP Courses', 'Honors'], ARRAY['Football', 'Basketball', 'Baseball', 'Soccer'], ARRAY['AP', 'Jesuit'], 'https://www.brophyprep.org', 'admissions@brophyprep.org', '(602) 264-5291', 'verified', 'official_website', true),
('Bentonville High School', 'High School', 'Bentonville', 'AR', 'South', ARRAY['9-12'], ARRAY['College Prep', 'AP Courses', 'STEM'], ARRAY['Football', 'Basketball', 'Soccer', 'Track'], ARRAY['AP', 'STEM'], 'https://bhs.bentonvillek12.org', 'bhs@bentonvillek12.org', '(479) 254-5600', 'verified', 'nces', true),
('Mission San Jose HS', 'High School', 'Fremont', 'CA', 'West', ARRAY['9-12'], ARRAY['College Prep', 'AP Courses', 'STEM'], ARRAY['Football', 'Basketball', 'Volleyball', 'Badminton'], ARRAY['AP', 'STEM Academy'], 'https://msj.fuhsd.org', 'info@fuhsd.org', '(510) 657-2700', 'verified', 'nces', true),
('Cherry Creek HS', 'High School', 'Greenwood Village', 'CO', 'West', ARRAY['9-12'], ARRAY['College Prep', 'AP Courses', 'IB'], ARRAY['Football', 'Basketball', 'Lacrosse', 'Soccer'], ARRAY['AP', 'IB'], 'https://creek.cherrycreekschools.org', 'creek@cherrycreekschools.org', '(720) 554-2200', 'verified', 'nces', true),
('Greenwich High School', 'High School', 'Greenwich', 'CT', 'Northeast', ARRAY['9-12'], ARRAY['College Prep', 'AP Courses', 'Honors'], ARRAY['Football', 'Basketball', 'Lacrosse', 'Swimming'], ARRAY['AP', 'Honors'], 'https://ghs.greenwichschools.org', 'ghs@greenwichschools.org', '(203) 625-8000', 'verified', 'nces', true),
('Charter School Wilmington', 'High School', 'Wilmington', 'DE', 'Northeast', ARRAY['9-12'], ARRAY['STEM', 'AP Courses'], ARRAY['Soccer', 'Basketball', 'Track'], ARRAY['STEM Focus', 'AP'], 'https://www.charterschool.org', 'info@charterschool.org', '(302) 651-2727', 'verified', 'official_website', true),
('Stanton College Prep', 'High School', 'Jacksonville', 'FL', 'South', ARRAY['9-12'], ARRAY['College Prep', 'AP Courses', 'IB'], ARRAY['Basketball', 'Volleyball', 'Track', 'Swimming'], ARRAY['AP', 'IB', 'Magnet'], 'https://stanton.duvalschools.org', 'stanton@duvalschools.org', '(904) 858-6200', 'verified', 'nces', true),
('Northview High School', 'High School', 'Johns Creek', 'GA', 'South', ARRAY['9-12'], ARRAY['College Prep', 'AP Courses', 'STEM'], ARRAY['Football', 'Basketball', 'Soccer', 'Tennis'], ARRAY['AP', 'STEM'], 'https://www.northviewhs.org', 'info@fultonschools.org', '(470) 254-2670', 'verified', 'nces', true),
('Punahou School', 'High School', 'Honolulu', 'HI', 'West', ARRAY['9-12'], ARRAY['College Prep', 'AP Courses', 'Liberal Arts'], ARRAY['Football', 'Basketball', 'Volleyball', 'Swimming'], ARRAY['AP', 'Private'], 'https://www.punahou.edu', 'admission@punahou.edu', '(808) 944-5711', 'verified', 'official_website', true),
('Boise High School', 'High School', 'Boise', 'ID', 'West', ARRAY['9-12'], ARRAY['College Prep', 'AP Courses', 'CTE'], ARRAY['Football', 'Basketball', 'Soccer', 'Track'], ARRAY['AP', 'Career Tech'], 'https://bhs.boiseschools.org', 'bhs@boiseschools.org', '(208) 854-4200', 'verified', 'nces', true),
('Walter Payton Prep', 'High School', 'Chicago', 'IL', 'Midwest', ARRAY['9-12'], ARRAY['College Prep', 'AP Courses', 'Honors'], ARRAY['Basketball', 'Volleyball', 'Track', 'Swimming'], ARRAY['AP', 'Selective'], 'https://www.paytonhs.org', 'payton@cps.edu', '(773) 534-0034', 'verified', 'nces', true),
('Carmel High School', 'High School', 'Carmel', 'IN', 'Midwest', ARRAY['9-12'], ARRAY['College Prep', 'AP Courses', 'IB'], ARRAY['Football', 'Basketball', 'Soccer', 'Swimming'], ARRAY['AP', 'IB'], 'https://chs.ccs.k12.in.us', 'chs@ccs.k12.in.us', '(317) 846-7721', 'verified', 'nces', true),
('Dowling Catholic HS', 'High School', 'West Des Moines', 'IA', 'Midwest', ARRAY['9-12'], ARRAY['College Prep', 'AP Courses', 'Honors'], ARRAY['Football', 'Basketball', 'Baseball', 'Track'], ARRAY['AP', 'Catholic'], 'https://www.dowlingcatholic.org', 'info@dowlingcatholic.org', '(515) 222-1093', 'verified', 'official_website', true),
('Blue Valley North HS', 'High School', 'Overland Park', 'KS', 'Midwest', ARRAY['9-12'], ARRAY['College Prep', 'AP Courses', 'STEM'], ARRAY['Football', 'Basketball', 'Soccer', 'Swimming'], ARRAY['AP', 'STEM'], 'https://bvn.bluevalleyk12.org', 'bvn@bluevalleyk12.org', '(913) 239-3400', 'verified', 'nces', true),
('DuPont Manual HS', 'High School', 'Louisville', 'KY', 'South', ARRAY['9-12'], ARRAY['College Prep', 'AP Courses', 'Magnet'], ARRAY['Football', 'Basketball', 'Track', 'Swimming'], ARRAY['AP', 'Magnet'], 'https://www.manualhs.com', 'manual@jefferson.kyschools.us', '(502) 485-8277', 'verified', 'nces', true),
('Boston Latin School', 'High School', 'Boston', 'MA', 'Northeast', ARRAY['9-12'], ARRAY['College Prep', 'AP Courses', 'Classical'], ARRAY['Football', 'Basketball', 'Lacrosse', 'Track'], ARRAY['AP', 'Classical'], 'https://www.bls.org', 'info@bls.org', '(617) 635-8895', 'verified', 'nces', true),
('Montgomery Blair HS', 'High School', 'Silver Spring', 'MD', 'Northeast', ARRAY['9-12'], ARRAY['College Prep', 'AP Courses', 'Magnet'], ARRAY['Football', 'Basketball', 'Soccer', 'Track'], ARRAY['AP', 'Magnet'], 'https://www.mbhs.edu', 'blair@mcpsmd.org', '(240) 740-7000', 'verified', 'nces', true),
('Detroit Country Day', 'High School', 'Beverly Hills', 'MI', 'Midwest', ARRAY['9-12'], ARRAY['College Prep', 'AP Courses', 'Honors'], ARRAY['Football', 'Basketball', 'Hockey', 'Lacrosse'], ARRAY['AP', 'Private'], 'https://www.dcds.edu', 'admissions@dcds.edu', '(248) 646-7717', 'verified', 'official_website', true);