-- Seed youth sports services data (15 entries) with correct data_source values
INSERT INTO public.youth_services_database (
  service_name, service_type, organization_name, city, state, region, programs_offered, age_ranges,
  sports_offered, facilities, cost_info, website, contact_email, contact_phone,
  verification_status, data_source, is_active
) VALUES
('AAU Basketball Atlanta', 'Sports', 'Amateur Athletic Union', 'Atlanta', 'GA', 'South', ARRAY['Basketball Training', 'Tournament Play'], ARRAY['8-18'], ARRAY['Basketball'], ARRAY['Indoor Courts', 'Training Facility'], 'Membership: $75/year', 'https://aaubasketball.org', 'atlanta@aaubasketball.org', '(404) 555-0100', 'verified', 'partner', true),
('AAU Basketball LA', 'Sports', 'Amateur Athletic Union', 'Los Angeles', 'CA', 'West', ARRAY['Basketball Training', 'Tournament Play'], ARRAY['7-18'], ARRAY['Basketball'], ARRAY['Multiple Gyms'], 'Membership: $75/year', 'https://aaubasketball.org', 'la@aaubasketball.org', '(213) 555-0200', 'verified', 'partner', true),
('AAU Basketball Chicago', 'Sports', 'Amateur Athletic Union', 'Chicago', 'IL', 'Midwest', ARRAY['Basketball Training', 'Tournament Play'], ARRAY['8-18'], ARRAY['Basketball'], ARRAY['Indoor Courts'], 'Membership: $75/year', 'https://aaubasketball.org', 'chicago@aaubasketball.org', '(312) 555-0300', 'verified', 'partner', true),
('Pop Warner Atlanta', 'Sports', 'Pop Warner Football', 'Atlanta', 'GA', 'South', ARRAY['Football', 'Cheer'], ARRAY['5-16'], ARRAY['Football', 'Cheerleading'], ARRAY['Football Fields'], 'Registration: $150-250/season', 'https://www.popwarner.com', 'atlanta@popwarner.com', '(404) 555-1100', 'verified', 'partner', true),
('Pop Warner LA', 'Sports', 'Pop Warner Football', 'Los Angeles', 'CA', 'West', ARRAY['Football', 'Cheer', 'Flag Football'], ARRAY['5-16'], ARRAY['Football', 'Cheerleading', 'Flag Football'], ARRAY['Football Fields'], 'Registration: $150-250/season', 'https://www.popwarner.com', 'la@popwarner.com', '(323) 555-1200', 'verified', 'partner', true),
('AYSO Region 16 LA', 'Sports', 'AYSO', 'Los Angeles', 'CA', 'West', ARRAY['Youth Soccer', 'Skills Training'], ARRAY['4-18'], ARRAY['Soccer'], ARRAY['Soccer Fields'], 'Registration: $125-175/season', 'https://www.ayso.org', 'region16@ayso.org', '(310) 555-1600', 'verified', 'partner', true),
('AYSO Region 100 SD', 'Sports', 'AYSO', 'San Diego', 'CA', 'West', ARRAY['Youth Soccer', 'Tournament Play'], ARRAY['4-18'], ARRAY['Soccer'], ARRAY['Soccer Fields'], 'Registration: $125-175/season', 'https://www.ayso.org', 'region100@ayso.org', '(619) 555-1700', 'verified', 'partner', true),
('YMCA Metro Atlanta', 'Community Center', 'YMCA', 'Atlanta', 'GA', 'South', ARRAY['Basketball', 'Swimming', 'After School'], ARRAY['5-18'], ARRAY['Basketball', 'Swimming', 'Soccer', 'Volleyball'], ARRAY['Gym', 'Pool', 'Courts'], 'Membership: $25-75/month', 'https://www.ymcaatlanta.org', 'info@ymcaatlanta.org', '(404) 588-9622', 'verified', 'partner', true),
('YMCA Greater LA', 'Community Center', 'YMCA', 'Los Angeles', 'CA', 'West', ARRAY['Basketball', 'Swimming', 'After School'], ARRAY['5-18'], ARRAY['Basketball', 'Swimming', 'Soccer', 'Track'], ARRAY['Gym', 'Pool', 'Fields'], 'Membership: $25-75/month', 'https://www.ymcala.org', 'info@ymcala.org', '(213) 622-9622', 'verified', 'partner', true),
('YMCA Chicago', 'Community Center', 'YMCA', 'Chicago', 'IL', 'Midwest', ARRAY['Basketball', 'Swimming', 'Youth Sports'], ARRAY['5-18'], ARRAY['Basketball', 'Swimming', 'Volleyball', 'Soccer'], ARRAY['Gym', 'Pool', 'Courts'], 'Membership: $25-75/month', 'https://www.ymcachicago.org', 'info@ymcachicago.org', '(312) 419-9622', 'verified', 'partner', true),
('Boys & Girls Club Atlanta', 'Community Center', 'Boys & Girls Clubs', 'Atlanta', 'GA', 'South', ARRAY['Sports', 'Education', 'Arts'], ARRAY['6-18'], ARRAY['Basketball', 'Football', 'Track', 'Soccer'], ARRAY['Gym', 'Computer Lab'], 'Free membership', 'https://www.bgcma.org', 'info@bgcma.org', '(404) 527-7100', 'verified', 'partner', true),
('Boys & Girls Club LA', 'Community Center', 'Boys & Girls Clubs', 'Los Angeles', 'CA', 'West', ARRAY['Sports', 'Education', 'Technology'], ARRAY['6-18'], ARRAY['Basketball', 'Soccer', 'Baseball', 'Volleyball'], ARRAY['Gym', 'Computer Lab'], 'Free membership', 'https://www.bgcla.org', 'info@bgcla.org', '(213) 896-0311', 'verified', 'partner', true),
('Boys & Girls Club Chicago', 'Community Center', 'Boys & Girls Clubs', 'Chicago', 'IL', 'Midwest', ARRAY['Sports', 'Education', 'Leadership'], ARRAY['6-18'], ARRAY['Basketball', 'Football', 'Track', 'Soccer'], ARRAY['Gym', 'Computer Lab'], 'Free membership', 'https://www.bgcc.org', 'info@bgcc.org', '(312) 235-8000', 'verified', 'partner', true),
('Atlanta Parks & Rec', 'Community Center', 'City of Atlanta', 'Atlanta', 'GA', 'South', ARRAY['Basketball', 'Football', 'Soccer', 'Swimming'], ARRAY['5-18'], ARRAY['Basketball', 'Football', 'Soccer', 'Swimming', 'Track'], ARRAY['Community Centers', 'Parks', 'Pools'], 'Free/Low-cost programs', 'https://www.atlantaga.gov/parks', 'parks@atlantaga.gov', '(404) 546-6813', 'verified', 'api', true),
('LA Parks & Recreation', 'Community Center', 'City of Los Angeles', 'Los Angeles', 'CA', 'West', ARRAY['Basketball', 'Soccer', 'Swimming', 'Tennis'], ARRAY['5-18'], ARRAY['Basketball', 'Soccer', 'Swimming', 'Tennis', 'Baseball'], ARRAY['Recreation Centers', 'Parks', 'Pools'], 'Free/Low-cost programs', 'https://www.laparks.org', 'rap.info@lacity.org', '(888) 527-2757', 'verified', 'api', true);