-- Populate expo_events table with NCRF 2025-2026 Expo Calendar events

INSERT INTO public.expo_events (
  title,
  description,
  event_type,
  location_name,
  address,
  city,
  state,
  zip_code,
  event_date,
  end_date,
  registration_required,
  max_attendees,
  contact_email,
  contact_phone,
  parking_info,
  accessibility_info,
  featured_colleges
) VALUES
-- 2025 Events
(
  'Los Angeles College Expo',
  'Join us for our kickoff expo in Los Angeles! Meet over 50+ colleges, get accepted on the spot, and access millions in scholarship opportunities. Some colleges waive application fees, and you''ll experience life-changing seminars with special celebrity guests and prizes.',
  'college_fair',
  'Los Angeles Convention Center',
  '1201 South Figueroa Street',
  'Los Angeles',
  'CA',
  '90015',
  '2025-01-18 10:00:00-08',
  '2025-01-18 14:00:00-08',
  true,
  2000,
  'info@ncrf.org',
  '(555) 123-4567',
  'Parking available at the convention center. $20 daily rate.',
  'Wheelchair accessible. ASL interpreters available upon request.',
  ARRAY['UCLA', 'USC', 'Cal State LA', 'Pepperdine', 'Loyola Marymount']
),
(
  'Fresno College Expo',
  'Central Valley''s premier college expo! Connect with over 50 colleges and universities, meet admissions counselors, and discover scholarship opportunities. Certificate and trade schools will also be present.',
  'college_fair',
  'Fresno Convention & Entertainment Center',
  '700 M Street',
  'Fresno',
  'CA',
  '93721',
  '2025-02-08 10:00:00-08',
  '2025-02-08 14:00:00-08',
  true,
  1500,
  'info@ncrf.org',
  '(555) 123-4567',
  'Free parking available in adjacent lots.',
  'Fully accessible venue with elevators and ramps.',
  ARRAY['Fresno State', 'UC Merced', 'Cal Poly', 'CSU Stanislaus']
),
(
  'Detroit College Expo',
  'Motor City College Expo featuring Michigan''s top institutions and national universities. Get accepted on the spot and explore millions in available scholarships. Special focus on engineering and automotive programs.',
  'college_fair',
  'Huntington Place',
  '1 Washington Boulevard',
  'Detroit',
  'MI',
  '48226',
  '2025-02-22 10:00:00-05',
  '2025-02-22 14:00:00-05',
  true,
  1800,
  'info@ncrf.org',
  '(555) 123-4567',
  'Parking garage attached to convention center. $15 daily.',
  'ADA compliant facility with accessible restrooms and seating.',
  ARRAY['University of Michigan', 'Michigan State', 'Wayne State', 'Oakland University']
),
(
  'Family Night Extravaganza',
  'Special evening event for the whole family! Bring parents, guardians, and siblings to explore college opportunities together. Features include parent financial aid workshops, student panels, entertainment, prizes, and special celebrity appearances. Dinner provided!',
  'college_fair',
  'Ontario Convention Center',
  '2000 East Convention Center Way',
  'Ontario',
  'CA',
  '91764',
  '2025-03-08 18:00:00-08',
  '2025-03-08 21:00:00-08',
  true,
  2500,
  'info@ncrf.org',
  '(555) 123-4567',
  'Ample free parking available.',
  'Family-friendly venue with nursing rooms and accessible facilities.',
  ARRAY['UC Riverside', 'Cal Poly Pomona', 'Azusa Pacific', 'University of Redlands']
),
(
  'Oakland College Expo',
  'Bay Area College Expo in Oakland! Meet representatives from over 50 colleges including HBCUs, UCs, CSUs, and private institutions. Some colleges waive application fees on-site. Life-changing seminars included.',
  'college_fair',
  'Oakland Convention Center',
  '550 10th Street',
  'Oakland',
  'CA',
  '94607',
  '2025-03-22 10:00:00-07',
  '2025-03-22 14:00:00-07',
  true,
  1800,
  'info@ncrf.org',
  '(555) 123-4567',
  'Parking available at nearby garages. BART accessible.',
  'Wheelchair accessible. Close to public transit.',
  ARRAY['UC Berkeley', 'Stanford', 'Mills College', 'Holy Names University']
),
(
  'New York College Expo',
  'East Coast''s premier college expo! Meet admissions teams from over 50 colleges and universities. Get accepted on the spot and discover millions in scholarships. Features top NYC institutions and national schools.',
  'college_fair',
  'Jacob K. Javits Convention Center',
  '429 11th Avenue',
  'New York',
  'NY',
  '10001',
  '2025-04-05 10:00:00-04',
  '2025-04-05 14:00:00-04',
  true,
  3000,
  'info@ncrf.org',
  '(555) 123-4567',
  'Paid parking available. Subway accessible.',
  'Fully accessible venue. Close to Penn Station.',
  ARRAY['Columbia University', 'NYU', 'CUNY Schools', 'Fordham', 'Pace University']
),
(
  'Houston College Expo',
  'Texas'' largest college expo! Connect with over 50 colleges, get accepted on-site, and access scholarship opportunities. Certificate and trade school representatives present. Special guest appearances.',
  'college_fair',
  'George R. Brown Convention Center',
  '1001 Avenida de las Americas',
  'Houston',
  'TX',
  '77010',
  '2025-04-19 10:00:00-05',
  '2025-04-19 14:00:00-05',
  true,
  2200,
  'info@ncrf.org',
  '(555) 123-4567',
  'Parking garage attached. Light rail accessible.',
  'ADA compliant with accessible facilities throughout.',
  ARRAY['University of Houston', 'Rice University', 'Texas Southern', 'Houston Baptist']
),
(
  'Phoenix College Expo',
  'Arizona''s premier college expo! Meet representatives from 50+ institutions including Arizona universities and national schools. On-site admissions and scholarship opportunities available.',
  'college_fair',
  'Phoenix Convention Center',
  '100 North 3rd Street',
  'Phoenix',
  'AZ',
  '85004',
  '2025-05-03 10:00:00-07',
  '2025-05-03 14:00:00-07',
  true,
  1600,
  'info@ncrf.org',
  '(555) 123-4567',
  'Multiple parking garages nearby. Light rail accessible.',
  'Fully accessible venue with covered walkways.',
  ARRAY['Arizona State University', 'University of Arizona', 'NAU', 'Grand Canyon University']
),
(
  'Atlanta College Expo',
  'Southern College Expo featuring HBCUs and top regional universities! Get accepted on the spot, explore millions in scholarships, and connect with certificate and trade schools. Life-changing seminars and prizes.',
  'college_fair',
  'Georgia World Congress Center',
  '285 Andrew Young International Boulevard NW',
  'Atlanta',
  'GA',
  '30313',
  '2025-05-17 10:00:00-04',
  '2025-05-17 14:00:00-04',
  true,
  2500,
  'info@ncrf.org',
  '(555) 123-4567',
  'Parking decks available. MARTA accessible.',
  'Wheelchair accessible with accessible parking.',
  ARRAY['Spelman College', 'Morehouse', 'Clark Atlanta', 'Georgia State', 'Emory']
),
(
  'Chicago College Expo',
  'Midwest''s largest college expo! Meet over 50 colleges and universities, get on-site admissions decisions, and access scholarship opportunities. Some colleges waive application fees.',
  'college_fair',
  'McCormick Place',
  '2301 South Martin Luther King Drive',
  'Chicago',
  'IL',
  '60616',
  '2025-06-07 10:00:00-05',
  '2025-06-07 14:00:00-05',
  true,
  2800,
  'info@ncrf.org',
  '(555) 123-4567',
  'Large parking facility on-site. Metra and CTA accessible.',
  'Fully accessible convention center.',
  ARRAY['University of Chicago', 'Northwestern', 'DePaul', 'Loyola Chicago', 'UIC']
),
(
  'Philadelphia College Expo',
  'Historic Philadelphia College Expo! Connect with 50+ colleges including Ivy League and local institutions. Get accepted on the spot and explore scholarship opportunities. Life-changing seminars included.',
  'college_fair',
  'Pennsylvania Convention Center',
  '1101 Arch Street',
  'Philadelphia',
  'PA',
  '19107',
  '2025-06-21 10:00:00-04',
  '2025-06-21 14:00:00-04',
  true,
  2000,
  'info@ncrf.org',
  '(555) 123-4567',
  'Multiple parking garages nearby. SEPTA accessible.',
  'ADA accessible facility in center city.',
  ARRAY['University of Pennsylvania', 'Temple', 'Drexel', 'La Salle', 'Villanova']
),
(
  'Miami College Expo',
  'South Florida''s premier college expo! Meet representatives from 50+ colleges, get accepted on-site, and discover millions in scholarships. Certificate and trade schools represented. Bilingual support available.',
  'college_fair',
  'Miami Beach Convention Center',
  '1901 Convention Center Drive',
  'Miami',
  'FL',
  '33139',
  '2025-07-12 10:00:00-04',
  '2025-07-12 14:00:00-04',
  true,
  2000,
  'info@ncrf.org',
  '(555) 123-4567',
  'Parking garage on-site. Metromover accessible.',
  'Fully accessible venue with oceanside location.',
  ARRAY['University of Miami', 'FIU', 'Florida Atlantic', 'Barry University']
),
(
  'Dallas College Expo',
  'North Texas College Expo featuring 50+ institutions! Get accepted on the spot, access scholarship opportunities, and meet with certificate and trade school representatives. Special celebrity guests and prizes.',
  'college_fair',
  'Kay Bailey Hutchison Convention Center Dallas',
  '650 South Griffin Street',
  'Dallas',
  'TX',
  '75202',
  '2025-07-26 10:00:00-05',
  '2025-07-26 14:00:00-05',
  true,
  2200,
  'info@ncrf.org',
  '(555) 123-4567',
  'Convention center parking available. DART rail accessible.',
  'Wheelchair accessible with accessible parking.',
  ARRAY['SMU', 'UT Dallas', 'UNT', 'TCU', 'Baylor']
),
(
  'STEAM Expo',
  'Special STEAM-focused college expo! Explore Science, Technology, Engineering, Arts, and Mathematics programs at top institutions. Hands-on demonstrations, tech company representatives, and scholarship opportunities. Perfect for students interested in STEM careers.',
  'college_fair',
  'San Jose Convention Center',
  '150 West San Carlos Street',
  'San Jose',
  'CA',
  '95113',
  '2025-08-09 10:00:00-07',
  '2025-08-09 14:00:00-07',
  true,
  2500,
  'info@ncrf.org',
  '(555) 123-4567',
  'Multiple parking garages nearby. VTA light rail accessible.',
  'Fully accessible Silicon Valley venue.',
  ARRAY['Stanford', 'UC Berkeley', 'Santa Clara University', 'San Jose State', 'Harvey Mudd']
),
(
  'San Diego College Expo',
  'Southern California''s beach city expo! Meet over 50 colleges and universities, get on-site admissions, and access scholarship opportunities. Some colleges waive application fees. Beautiful venue location.',
  'college_fair',
  'San Diego Convention Center',
  '111 West Harbor Drive',
  'San Diego',
  'CA',
  '92101',
  '2025-08-23 10:00:00-07',
  '2025-08-23 14:00:00-07',
  true,
  1800,
  'info@ncrf.org',
  '(555) 123-4567',
  'Parking available at convention center. Trolley accessible.',
  'Waterfront accessible venue.',
  ARRAY['UCSD', 'San Diego State', 'USD', 'Point Loma Nazarene']
),
(
  'Las Vegas College Expo',
  'Nevada''s premiere college expo! Connect with 50+ institutions, get accepted on the spot, and explore scholarship opportunities. Entertainment capital meets educational opportunity. Prizes and special guests!',
  'college_fair',
  'Las Vegas Convention Center',
  '3150 Paradise Road',
  'Las Vegas',
  'NV',
  '89109',
  '2025-09-06 10:00:00-07',
  '2025-09-06 14:00:00-07',
  true,
  2000,
  'info@ncrf.org',
  '(555) 123-4567',
  'Large parking facility available. Monorail accessible.',
  'Fully accessible venue on the Strip.',
  ARRAY['UNLV', 'Nevada State', 'NSC', 'Roseman University']
),
(
  'Seattle College Expo',
  'Pacific Northwest''s premier college expo! Meet representatives from 50+ colleges including Washington universities and national schools. On-site admissions and scholarship opportunities. Life-changing seminars.',
  'college_fair',
  'Washington State Convention Center',
  '705 Pike Street',
  'Seattle',
  'WA',
  '98101',
  '2025-09-20 10:00:00-07',
  '2025-09-20 14:00:00-07',
  true,
  1800,
  'info@ncrf.org',
  '(555) 123-4567',
  'Multiple parking garages nearby. Light rail accessible.',
  'Downtown accessible venue.',
  ARRAY['University of Washington', 'Seattle University', 'Seattle Pacific', 'UW Tacoma']
),
(
  'Community & Career Day',
  'Special community-focused event! Explore both traditional college pathways and career alternatives. Meet with trade schools, certificate programs, apprenticeship opportunities, and community colleges. Family-friendly with career counseling workshops.',
  'college_fair',
  'Riverside Convention Center',
  '3637 Fifth Street',
  'Riverside',
  'CA',
  '92501',
  '2025-10-04 10:00:00-07',
  '2025-10-04 14:00:00-07',
  true,
  1500,
  'info@ncrf.org',
  '(555) 123-4567',
  'Free parking available.',
  'Fully accessible community venue.',
  ARRAY['UC Riverside', 'Cal Baptist', 'Riverside Community College', 'Crafton Hills']
),
(
  'Denver College Expo',
  'Rocky Mountain College Expo! Meet over 50 colleges and universities, get accepted on the spot, and access millions in scholarships. Certificate and trade schools present. Special mountain state focus.',
  'college_fair',
  'Colorado Convention Center',
  '700 14th Street',
  'Denver',
  'CO',
  '80202',
  '2025-10-18 10:00:00-06',
  '2025-10-18 14:00:00-06',
  true,
  1600,
  'info@ncrf.org',
  '(555) 123-4567',
  'Convention center parking available. RTD light rail accessible.',
  'Accessible venue in downtown Denver.',
  ARRAY['University of Denver', 'CU Boulder', 'Colorado State', 'Regis University']
),
(
  'Boston College Expo',
  'New England''s premier college expo! Connect with 50+ institutions including prestigious Boston-area schools. Get accepted on the spot, explore scholarships, and meet with admissions counselors. Historic educational hub.',
  'college_fair',
  'Boston Convention & Exhibition Center',
  '415 Summer Street',
  'Boston',
  'MA',
  '02210',
  '2025-11-01 10:00:00-04',
  '2025-11-01 14:00:00-04',
  true,
  2200,
  'info@ncrf.org',
  '(555) 123-4567',
  'On-site parking. Silver Line bus accessible.',
  'Fully accessible waterfront venue.',
  ARRAY['Harvard', 'MIT', 'Boston University', 'Northeastern', 'Boston College']
),
-- 2026 Events
(
  'Washington D.C. College Expo',
  'Nation''s capital college expo! Meet representatives from 50+ colleges and universities including D.C. area schools and HBCUs. Get accepted on the spot and access scholarship opportunities. Special focus on political science and government programs.',
  'college_fair',
  'Walter E. Washington Convention Center',
  '801 Mount Vernon Place NW',
  'Washington',
  'DC',
  '20001',
  '2026-01-17 10:00:00-05',
  '2026-01-17 14:00:00-05',
  true,
  2500,
  'info@ncrf.org',
  '(555) 123-4567',
  'Parking garage on-site. Metro accessible.',
  'Fully accessible federal district venue.',
  ARRAY['Georgetown', 'George Washington', 'Howard University', 'American University', 'Catholic University']
);